version: '3'
services:
  parity1:
    build: parity
    ports:
      - "8541:8545"
  parity2:
    build: parity
    ports:
      - "8542:8545"
  redis:
    image: "redis:4"
  rabbit:
    image: "rabbitmq:3-management"
    ports:
      - "15672:15672"
  bridge:
    build: ..
    environment:
      - NODE_ENV=production
      - QUEUE_URL=amqp://rabbit
      - REDIS_URL=redis://redis
      - HOME_RPC_URL=http://parity1:8545
      - FOREIGN_RPC_URL=http://parity2:8545
      - HOME_BRIDGE_ADDRESS=0x32198D570fffC7033641F8A9094FFDCaAEF42624
      - FOREIGN_BRIDGE_ADDRESS=0x2B6871b9B02F73fa24F4864322CdC78604207769
      - ERC20_TOKEN_ADDRESS=0xdbeE25CbE97e4A5CC6c499875774dc7067E9426B
      - VALIDATOR_ADDRESS=0xaaB52d66283F7A1D5978bcFcB55721ACB467384b
      - VALIDATOR_ADDRESS_PRIVATE_KEY=8e829f695aed89a154550f30262f1529582cc49dc30eff74a6b491359e0230f9
      - REDIS_LOCK_TTL=1000
      - GAS_PRICE_SPEED_TYPE=standard
      - GAS_PRICE_FALLBACK=1
      - HOME_POLLING_INTERVAL=500
      - FOREIGN_POLLING_INTERVAL=500
      - ALLOW_HTTP=yes
    command: "true"
  bridge-erc:
    build: ..
    environment:
      - NODE_ENV=production
      - BRIDGE_MODE=ERC_TO_ERC
      - QUEUE_URL=amqp://rabbit
      - REDIS_URL=redis://redis
      - HOME_RPC_URL=http://parity1:8545
      - FOREIGN_RPC_URL=http://parity2:8545
      - HOME_BRIDGE_ADDRESS=0x1feB40aD9420b186F019A717c37f5546165d411E
      - FOREIGN_BRIDGE_ADDRESS=0xD0B9745831dDA9cbb47D0dEa904972cDcecc52e8
      - ERC20_TOKEN_ADDRESS=0x7777D2BF48993088dC1ceD832863b80427Ff5Ec9
      - BRIDGEABLE_TOKEN_ADDRESS=0x792455a6bCb62Ed4C4362D323E0590654CA4765c
      - VALIDATOR_ADDRESS=0xaaB52d66283F7A1D5978bcFcB55721ACB467384b
      - VALIDATOR_ADDRESS_PRIVATE_KEY=8e829f695aed89a154550f30262f1529582cc49dc30eff74a6b491359e0230f9
      - REDIS_LOCK_TTL=1000
      - GAS_PRICE_SPEED_TYPE=standard
      - GAS_PRICE_FALLBACK=1
      - HOME_POLLING_INTERVAL=500
      - FOREIGN_POLLING_INTERVAL=500
      - ALLOW_HTTP=yes
      - NUMBER_OF_WITHDRAWALS_TO_SEND=3
      - NUMBER_OF_DEPOSITS_TO_SEND=3
      - USER_ADDRESS=0xbb140FbA6242a1c3887A7823F7750a73101383e3
      - USER_ADDRESS_PRIVATE_KEY=63e48a8ba0b99e0377c6b483af4a072cbca5ffbcfdac77be72e69f4960125800
      - HOME_MIN_AMOUNT_PER_TX=0.01
      - FOREIGN_MIN_AMOUNT_PER_TX=0.01
    command: "true"
  e2e:
    build: .
    command: "true"
